Repository ZealandNaestved/DAT20-UP-projekt, pull requests merged in 2021-03, with the labels that each got.

#68 Update ENV06 ProcedureTilTidsregistrering.md
  09 Environment/ENV06 ProcedureTilTidsregistrering.md
Labels: documentation

#69 Procedure for issues
  09 Environment/ENV07 - ProcedureForIssues.md
Labels: documentation

#109 Tilføjet Domænemodel til usecase 2
  02 Requirements/REQ01_DM_DomaineModelUseCase02.vsdx
Labels: documentation

#124 Skiftede navn på REQ01_DM_DomaineModelUseCase02.vsdx til REQ04_DM_Dom…
  02 Requirements/REQ04_DM_DomaineModelUseCase02.vsdx
Labels: documentation

#100 Tilføjet den klasse der står for at launche main klassen i en jar fil.
  04 Implementation/src/hoekcel/MainJarClass.java
Labels: help wanted

#130 Create Test05_UseCase06.md
  05 Test/Test05_UseCase06.md
Labels: documentation

#149 Update UC-02_BeregningAfBruttofortjeneste.md til at være formel
  02 Requirements/Use Cases/UC-02_BeregningAfBruttofortjeneste.md
Labels: documentation

#132 Deployment procedure markdown
  06 Deployment/DP01_DeploymentProcedure.md
  assets/JarDeployment/,
  assets/JarDeployment/BilledeTilPunkt1.png
  assets/JarDeployment/BilledeTilPunkt2.png
  assets/JarDeployment/BilledeTilPunkt3.png
  assets/JarDeployment/BilledeTilPunkt4.png
  assets/JarDeployment/BilledeTilPunkt5.png
  assets/JarDeployment/BilledeTilPunkt8.png
Labels: documentation

#146 Excel Demo
  04 Implementation/ExcelDemo/.idea/.gitignore
  04 Implementation/ExcelDemo/.idea/compiler.xml
  04 Implementation/ExcelDemo/.idea/jarRepositories.xml
  04 Implementation/ExcelDemo/.idea/libraries/org_apache_poi_poi_4_1_1.xml
  04 Implementation/ExcelDemo/.idea/libraries/org_apache_poi_poi_ooxml_4_1_1.xml
  04 Implementation/ExcelDemo/.idea/misc.xml
  04 Implementation/ExcelDemo/.idea/uiDesigner.xml
  04 Implementation/ExcelDemo/exportExcelDemo.iml
  04 Implementation/ExcelDemo/pom.xml
  04 Implementation/ExcelDemo/src/main/java/Main.java
Labels: enhancement

#141 Tilføjet udkast til SSD1
  02 Requirements/REQ_10_SDD1_UseCase01SystemSequenceDiagram.vsdx
Labels: documentation

#142 SSD2 UseCase2 beregnBruttofortjeneste
  02 Requirements/REQ_11_SSD2_UseCase2BeregnBruttofortjeneste.vsdx
Labels: documentation

#157 Use case04 formel
  02 Requirements/Use Cases/UC-04 Beregn Indtjeningsbidrag.md
  02 Requirements/Use Cases/UC-04_BeregnIndtjeningsbidrag.md
Labels: documentation

#159 Tilføjet UC-01_BeregningAfOmkostninger
  02 Requirements/Use Cases/UC -01_BeregningAfOmkostninger.md
Labels: documentation

#147 Udkast til faseplan iteration 1
  08 Project Management/PM05_faseplanInitial.vsdx
Labels: help wanted

#166 Reupload af SSD1
  02 Requirements/REQ_10_SDD1_UseCase01SystemSequenceDiagram1.vsdx
Labels: documentation

#167 SSD2 is back
  02 Requirements/REQ_11_SSD2_UseCase2BeregnBruttofortjeneste.vsdx
Labels: documentation

#169 renamed SSD1
  02 Requirements/REQ_10_SDD1_UseCase01SystemSequenceDiagram.vsdx
Labels: documentation

#199 Oc 04
  02 Requirements/REQ15_OC04_OperationsContract_UseCase04.md
Labels: documentation

#216 OC5 til review tak! :o
  02 Requirements/REQ_18_OC05_OperationsContract5.md
  04 Implementation/src/hoekcel/MainJarClass.java
Labels: documentation

#201 SD til UseCase1
  02 Requirements/REQ15_SD_UseCase1SystemDiagram.vsdx
Labels: help wanted

#239 SSD5 for UC05
  02 Requirements/REQ20_SSD5_UseCase05ResultBeforeInterest.vsdx
Labels: enhancement

#204 Tilføjet DM04
  02 Requirements/REQ21_DM_DomæneModel04.png
  02 Requirements/REQ21_DM_DomæneModel04.vsdx
Labels: help wanted

#253 Skabt ikoner til brug i javaFX
  04 Implementation/FXassets/Add.png
  04 Implementation/FXassets/BlackPlus.png
  04 Implementation/FXassets/Export.png
  04 Implementation/FXassets/Info.png
  04 Implementation/FXassets/ToggleOff.png
  04 Implementation/FXassets/ToggleOn.png
  04 Implementation/FXassets/WhitePlus.png
Labels: enhancement

#182 Tilføjet SSD3
  02 Requirements/REQ14_SSD3_UseCase03SystemSequenceDiagram.vsdx
Labels: documentation

#261 Readme
  README.md
  assets/ReadmeAssets/afskrivningerReadme.png
  assets/ReadmeAssets/displayFunction.png
  assets/ReadmeAssets/displayResultat.png
  assets/ReadmeAssets/emptyDisplay.png
  assets/ReadmeAssets/fullview.png
  assets/ReadmeAssets/kapacitetsomkostninger.png
  assets/ReadmeAssets/omsætning.png
  assets/ReadmeAssets/vareforbrug.png
Labels: documentation

#263 Flere ikoner til javaFX
  04 Implementation/FXassets/Approve.png
  04 Implementation/FXassets/ApproveCircle.png
  04 Implementation/FXassets/Deny.png
  04 Implementation/FXassets/DenyCircle.png
Labels: enhancement

#264 Testcase 2 rettelser
  05 Test/Test02_Kundemøde1.md
Labels: documentation

#254 SD for OC06
  02 Requirements/REQ26_SD06_UseCase06.vsdx
Labels: help wanted

#265 Testcase 4 rettelser
  05 Test/Test03_Testcase04.md
  05 Test/Test03_Testcases.md
Labels: documentation

#285 Excel Feature til Review
  .gitignore
  .idea/libraries/org_apache_poi_poi_4_1_1.xml
  .idea/libraries/org_apache_poi_poi_ooxml_4_1_1.xml
  04 Implementation/ExcelDemo/.idea/.gitignore
  04 Implementation/ExcelDemo/.idea/compiler.xml
  04 Implementation/ExcelDemo/.idea/jarRepositories.xml
  04 Implementation/ExcelDemo/.idea/misc.xml
  04 Implementation/ExcelDemo/.idea/uiDesigner.xml
  04 Implementation/ExcelDemo/exportExcelDemo.iml
  04 Implementation/ExcelDemo/pom.xml
  04 Implementation/ExcelDemo/src/main/java/Main.java
  04 Implementation/src/hoekcel/Main.java
  04 Implementation/src/hoekcel/controller/MainController.java
  04 Implementation/src/hoekcel/controller/export/Excel.java
  04 Implementation/src/hoekcel/model/IncomeStatement.java
  04 Implementation/src/hoekcel/view/mainView.fxml
  DAT20-UP-projekt.iml
Labels: enhancement

#286 Error message update
  .idea/libraries/lib.xml
  01 Business Modeling/File.md
  04 Implementation/src/hoekcel/controller/MainController.java
  04 Implementation/src/hoekcel/model/IncomeStatementFactory.java
  DAT20-UP-projekt.iml
Labels: enhancement

#307 UC -07_Vareforbrug.md
  02 Requirements/Use Cases/UC -07_Vareforbrug.md
Labels: enhancement

#309 Replace icons
  04 Implementation/src/assets/Add.png
  04 Implementation/src/assets/Approve.png
  04 Implementation/src/assets/ApproveCircle.png
  04 Implementation/src/assets/BlackPlus.png
  04 Implementation/src/assets/Deny.png
  04 Implementation/src/assets/DenyCircle.png
  04 Implementation/src/assets/Export.png
  04 Implementation/src/assets/Info.png
  04 Implementation/src/assets/ToggleOff.png
  04 Implementation/src/assets/ToggleOn.png
  04 Implementation/src/assets/WhitePlus.png
  04 Implementation/src/hoekcel/view/mainView.fxml
Labels: enhancement
